### ISSUE TITLE
Change Zigbee name stylization from "ZigBee" to "Zigbee" in all docs and code

### ISSUE THREAD

**Issue by Gamester17** [dresden-elektronik/deconz-rest-doc#2]
Documentation and code need to be updated to say "Zigbee" instead of "ZigBee" as the official Zigbee Alliance changed the Zigbee name stylization from “ZigBee” to “Zigbee”, as in they are no longer writing Zigbee with a capital “B” in the middle of the name.

**Comment by manup** [comment]
Done in latest version.
